language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jsdevelooper/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsdevelooper/docker-react npm run test -- --coverage